name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['22.x']
        go: ['1.24']
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Clone repository
        uses: actions/checkout@v4
      -
        name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: ./lib/wasm/go.sum
          check-latest: true
          cache: true
      - 
        name: Copy wasm_exec.js
        if: matrix.os != 'windows-latest'
        run: cp $(go env GOROOT)/lib/wasm/wasm_exec.js ./src
      - 
        name: Copy wasm_exec.js (Windows)
        if: matrix.os == 'windows-latest'
        run: $src=[string]::Format('{0}\lib\wasm\wasm_exec.js', (go env GOROOT)); cp -Path $src -Destination .\src
      -
        name: Build Wasm file
        run: |
          go build -o ../../static/wasm.wasm
        working-directory: ./lib/wasm
        env:
          GOOS: js
          GOARCH: wasm
      - 
        run: |
          npm install
          npm run lint
          npm run compile
      - 
        name: Create .vsce Package
        run: npx vsce package -o freestylewiki-extension.vsix
      - 
        name: 'Upload Artifact'
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: freestylewiki-extension.vsix
          path: freestylewiki-extension.vsix
          retention-days: 5