name: build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['18.x']
        go: ['1.20']
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Clone repository
        uses: actions/checkout@v3
      -
        name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      -
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      -
        name: Build Wasm file
        run: |
          go build -o ../../static/wasm.wasm
        working-directory: ./lib/wasm
        env:
          GOOS: js
          GOARCH: wasm
      - 
        run: |
          npm install
          npm run lint
          npm run compile
      - 
        name: Create .vsce Package
        run: npx vsce package -o freestylewiki-extension.vsix
      - 
        name: 'Upload Artifact'
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: freestylewiki-extension.vsix
          path: freestylewiki-extension.vsix
          retention-days: 5