name: release
on: 
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Clone repository
        uses: actions/checkout@v4
      -
        name: Extract Tag Version
        id: tag
        run: echo "::set-output name=version::$(echo ${{ github.ref }} | sed -e 's/^refs\/tags\///')"
      -
        name: Output File Name
        id: filename
        run: echo "::set-output name=vsix::freestylewiki-extension_$(echo ${{ steps.tag.outputs.version }} | sed -e 's/^v//').vsix"
      -
        name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./lib/wasm/go.sum
          check-latest: true
          cache: true
      - 
        name: Copy wasm_exec.js
        run: |
          cp $(go env GOROOT)/lib/wasm/wasm_exec.js ./src
      -
        name: Build Wasm file
        run: |
          go build -o ../../static/wasm.wasm
        working-directory: ./lib/wasm
        env:
          GOOS: js
          GOARCH: wasm
      - 
        run: |
          npm install
          npm run lint
          npm run compile
      - 
        name: Create .vsce Package
        run: npx vsce package -o ${{ steps.filename.outputs.vsix }}
      - 
        name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: ${{ steps.filename.outputs.vsix }}
